#!/usr/bin/env php
<?php

require_once __DIR__.'/vendor/autoload.php';


$compiler = new Compiler();
$compiler->compile();


/**
 * The Compiler class compiles the Gitboard utility.
 * Heavily based on Goutte compiler
 * @author André Cianfarani <acianfa@gmail.com>
 */
class Compiler
{
    public function compile($pharFile = 'gitboard.phar')
    {
        if (file_exists($pharFile)) {
            unlink($pharFile);
        }
        $shebang = "#!/usr/bin/env php\n";
        file_put_contents("gitboard.php",str_replace($shebang,"",file_get_contents("gitboard.php")));
        $phar = new \Phar($pharFile, 0, 'Gitboard');
        $phar->setSignatureAlgorithm(\Phar::SHA1);

        $phar->startBuffering();

        // CLI Component files
        foreach ($this->getFiles() as $file) {
            $path = str_replace(__DIR__.'/', '', $file);
            $phar->addFromString($path, file_get_contents($file));
        }

        // Stubs
        $phar['_cli_stub.php'] = $this->getCliStub();
        $phar['_web_stub.php'] = $this->getWebStub();
        $phar->setDefaultStub('_cli_stub.php', '_web_stub.php');

        $phar->stopBuffering();
        file_put_contents("gitboard.php",$shebang.file_get_contents("gitboard.php"));

        unset($phar);
    }

    protected function getCliStub()
    {
        return "<?php ".$this->getLicense()." require_once __DIR__.'/vendor/autoload.php'; require_once __DIR__.'/gitboard.php'; __HALT_COMPILER();";
    }

    protected function getWebStub()
    {
        return "<?php throw new \LogicException('This PHAR file can only be used from the CLI.'); __HALT_COMPILER();";
    }

    protected function getLicense()
    {
        return '
    /*
     * Simple dashboard for a quick overview of Git projects.
     */';
    }

    protected function getFiles()
    {
        $files = array(
            'gitboard.php',
            'vendor/autoload.php',
            'vendor/composer/autoload_real.php',
            'vendor/composer/autoload_namespaces.php',
            'vendor/composer/autoload_classmap.php',
            'vendor/composer/ClassLoader.php',
            'vendor/sensiolabs/ansi-to-html/SensioLabs/AnsiConverter/AnsiToHtmlConverter.php',
            'vendor/sensiolabs/ansi-to-html/SensioLabs/AnsiConverter/Theme/Theme.php'
        );

        return $files;
    }
}